# Generated by Django 2.0.2 on 2020-05-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apihead',
            name='value',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='automationcasetestresult',
            name='header',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='请求头'),
        ),
        migrations.AlterField(
            model_name='automationhead',
            name='value',
            field=models.CharField(max_length=5000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='automationtestresult',
            name='header',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='请求头'),
        ),
    ]
