# Generated by Django 2.0.2 on 2020-07-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0004_auto_20200713_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaltoken',
            name='value',
            field=models.CharField(max_length=5000, verbose_name='值'),
        ),
    ]
