# Generated by Django 2.0.2 on 2020-08-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0005_auto_20200713_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationcasetestresult',
            name='caseUrl',
            field=models.TextField(blank=True, null=True, verbose_name='实际请求地址'),
        ),
    ]
