# Generated by Django 2.0.2 on 2020-08-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0006_automationcasetestresult_caseurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationcaseapi',
            name='exeSequence',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='执行顺序'),
        ),
    ]
