# Generated by Django 2.0.2 on 2020-08-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0009_auto_20200806_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationtesttask',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='automationtesttask',
            name='startTime',
        ),
        migrations.RemoveField(
            model_name='automationtesttask',
            name='unit',
        ),
        migrations.AlterField(
            model_name='automationtesttask',
            name='type',
            field=models.CharField(choices=[('interval', '循环'), ('cron', '定时')], max_length=50, verbose_name='类型'),
        ),
    ]
