# Generated by Django 2.0.2 on 2020-08-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0010_auto_20200806_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltoken',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='获取token的密码'),
        ),
        migrations.AddField(
            model_name='globaltoken',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='登录地址'),
        ),
        migrations.AddField(
            model_name='globaltoken',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='获取token的账号'),
        ),
        migrations.AlterField(
            model_name='automationtesttask',
            name='type',
            field=models.CharField(choices=[('circulation', '循环'), ('timing', '定时')], max_length=50, verbose_name='类型'),
        ),
    ]
