# Generated by Django 2.0.2 on 2020-08-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0011_auto_20200806_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaltoken',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='值'),
        ),
        migrations.AlterField(
            model_name='globaltoken',
            name='value',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='值'),
        ),
    ]
