# Generated by Django 2.0.2 on 2020-08-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0012_auto_20200806_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltoken',
            name='LastUpdateTime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最近修改时间'),
        ),
        migrations.AddField(
            model_name='globaltoken',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
