# Generated by Django 2.0.2 on 2020-08-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0013_auto_20200806_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationResponsParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='返回值Key')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='内容')),
                ('interrelate', models.BooleanField(default=False, verbose_name='是否关联')),
            ],
            options={
                'verbose_name': '存储校验返回值',
                'verbose_name_plural': '存储校验返回值',
            },
        ),
        migrations.CreateModel(
            name='PublicVariable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=50, null=True, verbose_name='变量名字')),
                ('value', models.TextField(blank=True, max_length=50, null=True, verbose_name='变量名字')),
                ('custom', models.TextField(blank=True, max_length=50, null=True, verbose_name='自定义')),
                ('automationTestCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.AutomationTestCase', verbose_name='用例')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.Project', verbose_name='所属项目')),
            ],
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='mockCode',
            field=models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('406', '406'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=50, null=True, verbose_name='HTTP状态'),
        ),
        migrations.AlterField(
            model_name='automationcaseapi',
            name='httpCode',
            field=models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('406', '406'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=50, null=True, verbose_name='HTTP状态'),
        ),
        migrations.AlterField(
            model_name='automationcasetestresult',
            name='httpStatus',
            field=models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('406', '406'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=50, null=True, verbose_name='http状态'),
        ),
        migrations.AlterField(
            model_name='automationtestresult',
            name='httpStatus',
            field=models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('406', '406'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=50, null=True, verbose_name='http状态'),
        ),
        migrations.AlterField(
            model_name='automationtestresult',
            name='statusCode',
            field=models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('406', '406'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=1024, null=True, verbose_name='期望HTTP状态'),
        ),
        migrations.AddField(
            model_name='automationresponsparameter',
            name='automationCaseApi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ResponsParameterList', to='api_test.AutomationCaseApi', verbose_name='接口'),
        ),
    ]
