# Generated by Django 2.0.2 on 2020-08-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0014_auto_20200813_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterVariable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=50, null=True, verbose_name='变量名字')),
                ('value', models.TextField(blank=True, max_length=50, null=True, verbose_name='变量名字')),
                ('custom', models.TextField(blank=True, max_length=50, null=True, verbose_name='自定义')),
                ('automationCaseApi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.AutomationCaseApi', verbose_name='接口')),
                ('automationTestCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.AutomationTestCase', verbose_name='用例')),
            ],
        ),
        migrations.RemoveField(
            model_name='publicvariable',
            name='automationTestCase',
        ),
        migrations.RemoveField(
            model_name='publicvariable',
            name='project',
        ),
    ]
