# Generated by Django 2.0.2 on 2020-08-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0015_auto_20200813_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationparameter',
            name='parInterrelate',
            field=models.BooleanField(default=False, verbose_name='是否参数关联'),
        ),
        migrations.AlterField(
            model_name='automationhead',
            name='interrelate',
            field=models.BooleanField(default=False, verbose_name='是否响应关联'),
        ),
        migrations.AlterField(
            model_name='automationparameter',
            name='interrelate',
            field=models.BooleanField(default=False, verbose_name='是否响应关联'),
        ),
    ]
