# Generated by Django 2.0.2 on 2020-08-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0016_auto_20200813_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltoken',
            name='GlobalHost',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api_test.GlobalHost', verbose_name='host'),
            preserve_default=False,
        ),
    ]
