# Generated by Django 2.0.2 on 2020-08-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0020_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_test.Project', verbose_name='项目'),
            preserve_default=False,
        ),
    ]
