# Generated by Django 2.0.2 on 2020-08-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0021_database_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='type',
            field=models.CharField(choices=[('1', 'Mysql'), ('2', 'SQL Server')], default=1, max_length=50, verbose_name='数据库类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='database',
            name='host',
            field=models.CharField(max_length=50, verbose_name='host'),
        ),
    ]
