# Generated by Django 2.0.2 on 2020-09-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0022_auto_20200818_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(max_length=50, verbose_name='自定义名称'),
        ),
        migrations.AlterField(
            model_name='publicvariable',
            name='custom',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='自定义'),
        ),
        migrations.AlterField(
            model_name='publicvariable',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='变量名字'),
        ),
        migrations.AlterField(
            model_name='publicvariable',
            name='value',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='变量名字'),
        ),
    ]
