# Generated by Django 2.0.2 on 2020-09-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0024_automationcaseapi__type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationcaseapi',
            name='_type',
        ),
        migrations.AddField(
            model_name='automationparameter',
            name='_type',
            field=models.CharField(blank=True, choices=[('Int', 'Int'), ('String', 'String'), ('Bool', 'Bool')], default='String', max_length=50, null=True, verbose_name='参数类型'),
        ),
    ]
