# Generated by Django 2.0.2 on 2020-11-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0025_auto_20200902_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationparameter',
            name='_type',
            field=models.CharField(blank=True, choices=[('Int', 'Int'), ('String', 'String'), ('Bool', 'Bool'), ('List', 'List'), ('Dict', 'Dict')], default='String', max_length=50, null=True, verbose_name='参数类型'),
        ),
    ]
